// This file is autogenerated. Changes will be overwritten.
#include "5OT6N72NQM/moc_qscadaboard.cpp"
#include "5OT6N72NQM/moc_qscadaboardcontroller.cpp"
#include "5OT6N72NQM/moc_qscadaboardmanager.cpp"
#include "AJN22ATYE5/moc_qscadabaseprefentity.cpp"
#include "CKU675I5TT/moc_qscadaobject.cpp"
#include "CKU675I5TT/moc_qscadaobjectinfo.cpp"
#include "CKU675I5TT/moc_qscadaobjectinfodialog.cpp"
